### ISSUE TITLE
Coordinates for mouse pressed and released

### ISSUE THREAD

**Issue by Zefk** [solarus-games/solarus#1001]
I noticed the :on_mouse_pressed(button,x,y), but I think it might be a little limited. I would use it to press buttons, but it is impossible to get certain coordinates for a button because it goes by quest size.
http://forum.solarus-games.org/index.php/topic,783.msg4295.html#msg4295

`function sol.main:on_mouse_pressed(button,x,y)
  if button == "left" and x <=50 and y<= 50 then
    print("left pressed")
  end 
 end`

A good enhancement for this would be  x1, x2, y1, y2  in tile coordinates to make a box/square and/or rectangle for the coordinates. These coordinates would be like (120,170,72,144) a rectangle around the middle of the screen. An okay size for a large button.

**EX:**
on_mouse_pressed(button,[x,y[quest size]], [x1,x2,y1,y2[coordinates]])

or

on_mouse_pressed_coordinates(button, [x1,x2,y1,y2[coordinates]])

**Comment by christopho** [comment]
I don't understand. When the user clicks somewhere, it is a single point, not a region.

**Comment by Zefk** [comment]
Apologies. I was incorrect. It is quite possible. This can be closed.

`function sol.main:on_mouse_pressed(button,x,y)

  if button == "left" and (x > 40 and x < 70) and (y > 16 and y < 43)  then
    print("left pressed")
  end 

 end`
