### ISSUE TITLE
problem when asking question with another question in the answer

### ISSUE THREAD

**Issue by yoshap** [solarus-games/solarus#1016]
Hello,
here is the bug I found : when I ask a first question with 3 answers, if one of these answers have another question with only 2 answers, the cursor moves like in the first question. The problem may be the structure of the dialog like the example below:

dialog{
  id = "test",
  text = [[
Test !
]]
}

dialog{
  id = "test.question",
  text = [[
Question avec nombre 
de réponses différentes :
]]
}

dialog{
  id = "test.question.1",
  text = [[
Voici la première question ?
$? Réponse 1
$? Réponse 2
$? Réponse 3
]]
}

dialog{
  id = "test.question.2",
  text = [[
Voici la deuxième question ?
$? Réponse 2.1
$? Réponse 2.2
]]
}

dialog{
  id = "test.reponse.1.1",
  text = [[
Réponse 1
]]
}

dialog{
  id = "test.reponse.1.2",
  text = [[
Réponse 2
]]
}

dialog{
  id = "test.reponse.1.3",
  text = [[
Réponse 3
]]
}

dialog{
  id = "test.reponse.2.1",
  text = [[
Réponse 2.1
]]
}

dialog{
  id = "test.reponse.2.2",
  text = [[
Réponse 2.2
]]
}

And here is the code for the dialog in the map : 

function test:on_interaction()
  game:start_dialog("test.question", function() game:on_dialog_finished(dialog)
    game:start_dialog("test.question.1",function(reponse_1)
      if reponse_1 == 2 then
        game:start_dialog("test.question.2", function(reponse_2)
          if reponse_2 == 2 then
            game:start_dialog("test.reponse.2.1")
          elseif reponse_2 == 3 then
            game:start_dialog("test.reponse.2.2")
          end
        end)
      elseif reponse_1 == 3 then
         game:start_dialog("test.reponse.1.2")
      elseif reponse_1 == 4 then
         game:start_dialog("test.reponse.1.3")
      end
    end)
  end)
end

**Comment by MetalES** [comment]
Are you using a custom script for the dialog ?
If yes, can you show the on_command_pressed function as well as the thing that parse how many answer there is

**Comment by Diarandor** [comment]
In the end this was an script bug. I opened an issue in the correct repo:
https://github.com/solarus-games/solarus-alttp-pack/issues/6
