### ISSUE TITLE
Load time in Solarus 1.5 using tilesets with large dimensions

### ISSUE THREAD

**Issue by ffomega** [solarus-games/solarus#1019]
It it takes between 3-6 seconds to load maps using Full Hyrule including transitioning between scrolling maps (the dimensions of the tileset image are 1584 x 4096 as of latest update, and it causes a 1 second lag whenever the Hero performs any actions for the first time (other than walking around) and a half-to-full second lag for the first time he interacts with a destructible object or grass (lifting, cutting, traversing.

**Comment by christopho** [comment]
Maps with your Full Hyrule outside tileset take about 0.5 second to load on my machine, which is still slow.

**Comment by christopho** [comment]
Tilesets are now kept in a cache. Loading maps is now costly only their tileset is used for the first time (0.5 s on my machine).
Loading maps whose tileset is already known should now be immediate.
