### ISSUE TITLE
build error on osx

### ISSUE THREAD

**Issue by rekcah1986** [solarus-games/solarus#1053]
**localhost:build XmacZone$ make**
Scanning dependencies of target solarus
[  0%] Building CXX object CMakeFiles/solarus.dir/src/entities/AnimatedTilePattern.cpp.o
...
[ 36%] Building CXX object CMakeFiles/solarus.dir/src/lowlevel/ItDecoder.cpp.o
/Users/XmacZone/Documents/solarus/src/lowlevel/ItDecoder.cpp:19:10: fatal error: 'stdafx.h' file not found
#include <stdafx.h>  // These two headers are with the libmodplug ones.
         ^
1 error generated.
make[2]: *** [CMakeFiles/solarus.dir/src/lowlevel/ItDecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/solarus.dir/all] Error 2
make: *** [all] Error 2

**And the libmodplug info:**
localhost:build XmacZone$ brew info libmodplug
libmodplug: stable 0.8.8.5 (bottled)
Library from the Modplug-XMMS project
https://modplug-xmms.sourceforge.io/
/usr/local/Cellar/libmodplug/0.8.8.5 (14 files, 343.4KB) *
  Poured from bottle on 2017-04-25 at 19:20:44
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libmodplug.rb

**Comment by ekureina** [comment]
Try changing the line to #inclue <libmodplug/stdafx.h> or to delete it all together and see if you get the error still.

**Comment by christopho** [comment]
The stdafx.h header is needed. It is provided with libmodplug, as the comment says.
I maintain a fork of libmodplug and the header is here: https://github.com/solarus-games/libmodplug/blob/master/src/libmodplug/stdafx.h

**Comment by Nate-Devv** [comment]
I understand.  According to the Homebrew tar, they are storing the header in a sub folder called libmodplug on Macs.  So we either need to add a conditional for it, or direct Mac users to your fork.
