### ISSUE TITLE
sprite:set_animation callback not working when changing the tunic sprite id

### ISSUE THREAD

**Issue by MetalES** [solarus-games/solarus#1054]
Setting a callback for an animation

sprite:set_animation("animation", function()
  blabla
end)

Will not work if we chage the tunic sprite id when playing this animation.
The animation is resetted to frame 0 but the callback will never be called

**Comment by christopho** [comment]
This is normal because changing the tunic sprite id restarts the animation. You have to change the tunic sprite id before starting an animation.

**Comment by christopho** [comment]
Actually the reason why this is normal is that the sprite has changed, it is a different instance after you change the tunic sprite id.
