### ISSUE TITLE
sol.video.set_window_size() does not change quest viewport

### ISSUE THREAD

**Issue by wrightmat** [solarus-games/solarus#1060]
sol.video.set_window_size() doesn't actually allow the player to see more of the quest if setting above the quest size. See http://forum.solarus-games.org/index.php/topic,989.0.html

**Comment by christopho** [comment]
But the purpose of sol.video.set_window_size() is not to see more or less quest content, it only changes the scaling factor of the image.
The quest size cannot be changed at runtime (yet).

**Comment by wrightmat** [comment]
To me, that's non-intuitive. set_window_size() and any scaling should be independent - maybe a second function of set_window_scaling().

**Comment by christopho** [comment]
The window size and the quest size are independent. The quest size is the size of the logical area before scaling and the window size is the actual size of the window after scaling.

We could make a function set_window_scaling(scaling) that does set_window_size(get_quest_size() * scaling).

Changing the quest size at runtime is a different matter, there is an issue for that: #1027

**Comment by wrightmat** [comment]
I shall wait for issue 1027 then :) Thanks!

**Comment by christopho** [comment]
Okay, can I close this one then @wrightmat?

**Comment by wrightmat** [comment]
Yes. I believe between set_window_size and the eventual set_quest_size, we should be able to achieve any viewport we'd like. Thank you!
