### ISSUE TITLE
sol.audio.play_music : second argument bug

### ISSUE THREAD

**Issue by potamouch** [solarus-games/solarus#1061]
The second argument of this method can not be a string of character contrary to what is marked in the documentation.

Sample : sol.audio.play_music("let_the_journey_begin", "overworld")

**Comment by Diarandor** [comment]
But the Lua API does not say that the second argument can be a string.
http://www.solarus-games.org/doc/1.5/lua_api_audio.html#lua_api_audio_play_music
It says: function or boolean, optional.

**Comment by christopho** [comment]
Woops :)
