### ISSUE TITLE
Feature request: streams allowing movement should not center the hero

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#1063]
It is not very natural to see the hero forced to be centered on certain stream entities if he can move (for instance, for water or wind currents). Actually, it is very annoying to move the hero in these cases. (The centering of the hero only happens in direction perpendicular to the stream direction.)

Feature request: streams allowing movement should not center the hero. The centering of the hero should only happen for streams not allowing movement.

**Comment by christopho** [comment]
The centering could be optional.
