### ISSUE TITLE
Feature request: allow to get tile patterns at a given position

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#1065]
Feature request: allow to get tile patterns at a given position.
Some function like this could be helpful:
map:get_tile_pattern_id(x, y, layer)

This is what I am trying to do:
I was trying to code a shovel item that detects the prefix of the pattern of a tile entity (to know if it represents a sand tile or not, and in that case, replace it by a dynamic tile). But there is no way to get tiles, and right now there is no way to get the pattern of a tile (I was trying this from the tile metatable, but the built-in function to get the pattern id is not defined); but this way of doing things is probably not good. I think it would be better to have a function "map:get_tile_pattern_id(x, y, layer)" to get the pattern id of the upper tile (of that layer) at that position, and then create a dynamic tile for the hole made by the shovel (the shovel will check the pattern id at 4 corner points of a 16x16 rectangle). Another option would be to allow getting tiles with "map:get_tile(x, y, layer)" and define some functions to get the pattern_id and other things.

EDIT: the function I need should also check other entities with ground features, just in case there is some entity with custom ground over the tiles (this includes dynamic tiles, custom entities, etc).

**Comment by christopho** [comment]
Tiles no longer exist at runtime because they are optimized out. You can detect their ground with map:get_ground(). Custom grounds will probably help to implement the shovel.

If you really want to know the exact tile pattern at a given position, it is actually possible to implement the function in Lua by parsing the map and tileset files.

**Comment by Diarandor** [comment]
Ok, you are right. It will be much better to define a custom ground for sand, so I am closing this request.
