### ISSUE TITLE
Bug avec les entités destructibles

### ISSUE THREAD

**Issue by dprogames** [solarus-games/solarus#1067]
Dans un de mes projet, j'ai remarqué que les entités destructibles (vases/ buissons) qui se régénère bug lorsqu'on les prend en mains. L'animation avec le son de la destruction se lance au moment où on l'attrape aux positions de l'entité. Le héros récupère le vase (ou le buisson) et peut le jeté normalement quand même.
![2017-07-31_22h18_49](https://user-images.githubusercontent.com/27856320/28796572-65f0723a-763e-11e7-9e5f-b5fc80f98d13.png)

**Comment by christopho** [comment]
Ah oui je comprends, en fait c'est fait exprès car à la base cette régénération était faite pour les choux-péteurs. Et on a bien l'animation du buisson coupé au moment où on le soulève.
