### ISSUE TITLE
ppa does not work on ubuntu artful 17.10

### ISSUE THREAD

**Issue by olymk2** [solarus-games/solarus#1150]
complains its missing a release file
````
sudo apt update
Ign:1 http://ppa.launchpad.net/nate-devv/solarus/ubuntu artful InRelease
Hit:2 http://gb.archive.ubuntu.com/ubuntu artful InRelease                                              
Err:3 http://ppa.launchpad.net/nate-devv/solarus/ubuntu artful Release                                  
  404  Not Found
Get:4 http://gb.archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]                         
Hit:5 http://gb.archive.ubuntu.com/ubuntu artful-backports InRelease                                    
Hit:6 http://security.ubuntu.com/ubuntu artful-security InRelease              
Get:7 http://gb.archive.ubuntu.com/ubuntu artful-updates/main i386 Packages [212 kB]
Get:8 http://gb.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages [216 kB]
Reading package lists... Done                                                      
E: The repository 'http://ppa.launchpad.net/nate-devv/solarus/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
````

**Comment by ekureina** [comment]
I haven't updated the PPA in a relatively long time. I don't really plan to update it, as it's a pain to upload packages for multiple Ubuntu versions, and I'd like to keep the repository for Debian and Ubuntu in a similar place. Try [this](https://software.opensuse.org//download.html?project=home%3Anate-devv%3Asolarus-debian&package=solarus) repository instead.

**Comment by olymk2** [comment]
That repository gives different issue, as for the ppa you don't really need to maintain the older distros leave them with the older versions thats what happens in the main repositories anyway :)

If this is not simple to fix i may try compiling from source just prefer to use packages.

````
Selecting previously unselected package solarus.
(Reading database ... 263434 files and directories currently installed.)
Preparing to unpack solarus_1.5.3-2_amd64.deb ...
Unpacking solarus (1.5.3-2) ...
dpkg: dependency problems prevent configuration of solarus:
 solarus depends on libqt5core5a (>= 5.9.0~beta); however:
  Package libqt5core5a is not installed.
 solarus depends on libqt5widgets5 (>= 5.2); however:
  Package libqt5widgets5 is not installed.
 solarus depends on libsolarus (= 1.5.3-2); however:
  Package libsolarus is not installed.

dpkg: error processing package solarus (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu5) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Errors were encountered while processing:
 solarus
````

**Comment by ekureina** [comment]
Looks like you grabbed just the binary, if you had the repository enabled apt-get should have resolved those dependencies. If you want to use the PPA, installing from the xenial packages should work. It'll take me a little while to upload artful packages, I can probably get them done on Friday/Saturday. Here's how to enable the opensuse repository:
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/nate-devv:/solarus-debian/xUbuntu_17.10/ /' > /etc/apt/sources.list.d/home:nate-devv:solarus-debian.list"
sudo apt-get update
sudo apt-get install solarus
```
If you want to build the packages yourself, the one for solarus is [here](https://build.opensuse.org/package/show/home:nate-devv:solarus-debian/solarus).

**Comment by olymk2** [comment]
I did try that, unfortunately seem ubuntu does not like the repo because its not signed.
````
E: The repository 'http://download.opensuse.org/repositories/home:/nate-devv:/solarus-debian/xUbuntu_17.10  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
````

are there build instructions ? i could not see any in the readme.

**Comment by ekureina** [comment]
That's weird, it should be signed... it has instructions for getting the keys.
In any case, you'll want to get the build dependencies from compilation.txt: `build-essential cmake
libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libluajit-5.1-dev
libphysfs-dev libopenal-dev libvorbis-dev libmodplug-dev
qtbase5-dev qttools5-dev qttools5-dev-tools`
If you want to build the packages, you'll also want the `devscripts` package.

You can just download the debian.tar.xz and the orig.tar.gz tarballs from the link I shared in my last post.
Extract the folder inside the orig.tar.gz and extract the debian folder from within the debian.tar.xz into the extracted folder.

At that point, you should be able to just run `debuild -b -us -uc` in the folder, and it should generate the packages. You'll want to install the libsolarus package before the solarus one.
