### ISSUE TITLE
Invalid PNG causes game to crash without an error

### ISSUE THREAD

**Issue by alexgleason** [solarus-games/solarus#1194]
I spent a few hours on this one today. At one point I did `touch tilesets/mymap.entities.png` to suppress the error of not having one, then I did a bunch of other stuff, then the quest wouldn't run and I had to frantically guess and check to figure out what I did wrong.

I'm okay with it crashing for this, but sending an error here (eg *"Invalid PNG file"*) would be *very helpful* to prevent this. Thank you!

**Comment by christopho** [comment]
Already fixed in dev branch. The .entities.png file is now optional.
