### ISSUE TITLE
Add a function surface:get_pixels()

### ISSUE THREAD

**Issue by vlag** [solarus-games/solarus#452]
This function will be useful to be able to set a personal "software" filter in lua, like a greyscale, light or contrast filter.
It can return 2 values : a pixel buffer and the pixel format associated.

**Comment by christopho** [comment]
I am keeping this bug active because the work is not finished, we must
- [x] check the function on Mac OS X @vlag
- [ ] add the support of optional parameters x, y
- [ ] update the Lua API documentation

**Comment by christopho** [comment]
@vlag Are the unit tests all okay on Mac OS X?

**Comment by vlag** [comment]
I should get my MacBook back for the end of the month, but I can mount a VM if the answer is needed to make a release sooner.

**Comment by christopho** [comment]
@vlag No problem, it can wait for the end of the month.

**Comment by wrightmat** [comment]
@vlag Any update on this?

**Comment by vlag** [comment]
I just noticed that you are still waiting for me, what should I do to validate the test ?

**Comment by christopho** [comment]
Simply run the unit tests (ctest) and check if they are all okay. Thanks

**Comment by vlag** [comment]
100% tests passed with the 1.5.3 release on OSX, I think we're good :)

**Comment by christopho** [comment]
Done
