### ISSUE TITLE
Allow to modify arbitrary surfaces from Lua

### ISSUE THREAD

**Issue by Renkineko** [solarus-games/solarus#466]
We should be able to manipulate surfaces like remove some regions from a drawn surface. Unavoidable if you want to add some "complex" graphic effects (example : for now, in ZSDX, darkness is managed with some sprites completely black at dimensions of screen, with a transparent space where the hero is, but if you want to apply the same principle to torchlight, the two transparents parts of the two sprites will conflict).

Feel free to edit this issue if it is unclear ^^'

**Comment by christopho** [comment]
Done (thanks @stdgregwar!)
