### ISSUE TITLE
Request: more customizable streams.

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#639]
Hi! I have some requests concerning streams.

First, there should be some optional property of custom entities to make streams affect some of them. (There is already a similar issue: "Enemy should be influenced by streams".)

Second, I realized that, when the hero is on the stream, the stream centers the hero in the 8x8 grid. Maybe this is fine for conveyor belts that freeze the hero, but it is quite unnatural to simulate air/water streams. That is why I ask for another optional property of streams, to change this behavior of the stream, if it is needed.

Third, I ask for another optional property of streams (but this one is not important for my purposes). Currently, when the hero uses the sword on a stream, he stops moving during the action. This is fine for some situations, but not in general. For example, to program "wind enemies" that can push the hero with streams into holes, the player could cheat using the sword to avoid being pushed. (The good behavior would be as in level 3 of Link's awakening, where using the sword or jumping stops moving the hero on conveyor belts, but that does not happen with the enemies that push/attract the hero with air.)

My last request is making directions of streams more customizable (to simulate air streams). For example, target-streams that move the hero towards a target (or in opposite direction), or streams with circular trajectory (like movements). Maybe there should be two different types of streams, because this is very different from streams used to simulate conveyor belts.

(Probably I asked too many things, and some of them could be too hard to program, but they would improve considerably the customization of streams.)

**Comment by Diarandor** [comment]
Currently I am using the scripts of custom entities for the customizations of streams that I needed. You can close this issue (unless other people disagree).

**Comment by christopho** [comment]
It is nice if custom entities are able to do better :)
I am still keeping the issue open because more customization would be useful.

**Comment by christopho** [comment]
Closing this issue, #1063 will be enough.
