### ISSUE TITLE
Feature request: sprite:set_opacity(opacity)

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#702]
It would be useful to have a method sprite:set_opacity(opacity). 

For instance, if we make a falling rock, it would be nice to draw the shadow in the upper layer with some transparency. (The only way to do it now is using a surface.)

**Comment by Zakarisz** [comment]
It will be useful to draw animated overlays (rain, snow, ...)
A way to draw it without the method is to set opacity in the png file.
But with this method, it will be possible to change dynamically the opacity.

**Comment by Diarandor** [comment]
Or even better, we should allow this for all drawables: "drawable:set_opacity(opacity)".
