### ISSUE TITLE
Problem with ground detection after hero:unfreeze()

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#827]
Hi! 

If we script a jump while the hero is frozen and then we unfreeze, the hero does not fall on holes if the jump finishes above a hole (only the falling sound is played), the hero can walk over a small rectangle without falling. I am using this to script the boots + feather combined ability, where I need to freeze the hero to keep the direction. I do not have this problem if I do not freeze the hero, which was the case of my scripted feather, where I do not freeze the hero. In both scripts (the feather script, and the one of the long jump that combines boots + feather) I use a custom entity with solid ground under the hero to allow him not to fall on bad grounds, and this entity is removed when the jump ends; this custom entity is probably related to that small rectangle where the hero can walk after the jump, even if the jump ends over a hole, and this problem disappears if the hero is not frozen as I said before.

I suspect that either the ground is not being updated when the hero is unfrozen or something like that, if this is related to the modified ground of the custom entity. Or maybe I am wrong and this is not related to that custom entity, but in any case there is some problem with the detection of the ground after unfreezing the hero.

I can send you my data if you need it to test this possible bug.

**Comment by MetalES** [comment]
Yes, I confirm this bug, I had this same thing while reworking some items (Bow, Hookshot & Boomerang). I had to do some wizzard thing to get it to work properly (The difference is that I didn't use a custom entity bellow the hero, but it seems that the bug is still present). Else the item would continue, and this is something related to unfreeze()

**Comment by Diarandor** [comment]
Thanks for confirming this bug. So we now know that the bug is related to the functions freeze/unfreeze.

**Comment by Diarandor** [comment]
I found a workaround for this problem: after unfreezing, we just create a custom entity with "traversable" ground under the hero and immediately destroy it. The engine will immediately notify that the ground under the hero has changed after removing the entity.

**Comment by christopho** [comment]
I just tested it and actually I don't reproduce the bug. Here is my code:

    -- Freeze the hero.
    hero:freeze()
    assert_equal(hero:get_state(), "frozen")

    -- Make him jump while frozen.
    local movement = sol.movement.create("jump")
    movement:set_direction8(0)
    movement:set_distance(48)
    movement:start(hero, function()

      -- He arrived on a hole and should be in state falling now.
      assert_equal(hero:get_state(), "falling")

      -- Unfreeze the hero: he is now free.
      hero:unfreeze()
      assert_equal(hero:get_state(), "free")

      -- At the next cycle, he should be falling again.
      sol.timer.start(10, function()
        assert_equal(hero:get_state(), "falling")
        sol.main.exit()
      end)
    end)

After this issue was opened, there were a lot of fixes about ground detection. So I think the issue was fixed in the meantime. Can you check again @Diarandor @MetalES?
Thanks

**Comment by Diarandor** [comment]
Maybe I forgot to mention it explicitly, but I am not using the built-in jump, but a custom jump. Besides, the jump is just which do NOT produce the bug. I only have this problem while sidewalking (with custom weapons like magnet, custom sword, etc), after unfreezing. I tried to reproduce the bug again, but I cannot reproduce it on hole grounds; however, it does happen in deep water tiles if you do not have the swim ability (I did not test on lava), so there is still a bug.

Should I send you my data so you can reproduce the problem?

**Comment by christopho** [comment]
My code is a custom jump (I did not use hero:start_jumping()) but I tested it on holes, not on water so I will try with water now. Thanks

**Comment by Diarandor** [comment]
Maybe the fact that I am still using an item while the hero is in "free" state has something to do, I don't know.

**Comment by christopho** [comment]
I was able to reproduce it with water (and lava) and I fixed it.
