### ISSUE TITLE
Make "tileset.entities.png" files optional

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#884]
Make entities file of a tileset (i.e., the files of name "tileset_name.entities.png") optional.

Remark: The game still runs perfectly if these files are missing (and the corresponding error is given in error.txt, something like "Error: Missing entities image for tileset 'overworld': tilesets/overworld.entities.png").

**Comment by alexander-b** [comment]
I think it would still be useful to know that it's missing.

**Comment by Diarandor** [comment]
In my opinion, there should be an error only if that file is needed and not found.

**Comment by alexander-b** [comment]
Hmm maybe. How about moving the error into get_entities_image() instead of having it in load()?
