### ISSUE TITLE
Launcher: allow to start a quest when pressing "Enter" key or mouse double click

### ISSUE THREAD

**Issue by Diarandor** [solarus-games/solarus#949]
Feature request:
When using the Launcher, if a quest is selected, allow to start the selected quest in any of these cases:
1) if "Enter" key is pressed
2) if we make double click with the mouse

PS: I do not know if this issue should be here (for the engine) or for the editor. Maybe this is the wrong place.

**Comment by christopho** [comment]
It is in the engine yes.
