### ISSUE TITLE
Crash when a carried bomb with custom sprite explodes

### ISSUE THREAD

**Issue by christopho** [solarus-games/solarus#953]
Can be reproduced with the sample quest (dev branch):

Diarandor_PC	you can reproduce it with the sample quest: take a bomb and let it explode when the hero is carrying it
Diarandor_PC: I changed the sprite of the bomb to use mine instead of the previous one. but there is a bug: if you let the bomb explode while the hero is carrying it the bug says: "Entity not found in Z cache"

**Comment by MetalES** [comment]
Hmmm, it only crash when the hero is stopped, was able to reproduce it as well
