### ISSUE TITLE
Rename hero:unfreeze() to hero:start_free()

### ISSUE THREAD

**Issue by christopho** [solarus-games/solarus#994]
hero:unfreeze() is misleading. It can actually be used from any previous hero state and its effect it to start the "free" state.

**Comment by Diarandor** [comment]
Another nice option is "hero:set_state(state)", where the possible values for the state are: "free", "frozen", and maybe some others. Setting the state as "free" would be equivalent to "hero:unfreeze()", and setting the state as "frozen" would be equivalent to "hero:freeze()". This syntax can also be extended later, either in C++ or in the Lua part, to allow setting more states.

Another possible syntax is "hero:set_free([bool])" or "hero:set_frozen([bool])", where the boolean is optional. But I personally like more "hero:set_state(state)".

**Comment by christopho** [comment]
I am not sure about hero:set_state() because lots of states need parameters to start. This is why there are separate functions.

Anyway, I changed my mind about this issue. hero:unfreeze() and hero:start_free() (if we add it one day) are different. hero:unfreeze() actually sets the appropriate state depending on the ground, whereas hero:start_free() would force the free state (ignoring the ground).
