### ISSUE TITLE
Misaligned ground check

### ISSUE THREAD

**Issue by mattias-p** [solarus-games/solarus#995]
In the following map the floor is split by an eight pixels wide chasm starting at y=8 and ending at y=15. Across this chasm 24 blocks are created at pixel intervals starting from y=0 until y=23.

From these blocks, 10 blocks remain on the north side, 8 fall into the chasm, and 6 remain on the south side. 

I would have expected the blocks falling down to be exactly the ones whose origins are over the chasm. In other words I'd expect 8 blocks in each of the three sets.

```
-- test.dat
properties{
  x = 0,
  y = 0,
  width = 384,
  height = 240,
  min_layer = 0,
  max_layer = 2,
  tileset = "dungeon_brick_blue_1",
}

tile{
  layer = 1,
  x = 0,
  y = 0,
  width = 384,
  height = 240,
  pattern = "floor.16",
}

tile{
  layer = 1,
  x = 0,
  y = 8,
  width = 384,
  height = 8,
  pattern = "hole",
}

destination{
  name = "destination",
  layer = 1,
  x = 168,
  y = 61,
  direction = 1,
}
```

```
-- test.lua
local map = ...

function map:on_started()
  for y = 0, 23  do
    map:create_block({
      layer = 1,
      x = 16 * y + 8,
      y = y,
      sprite = 'entities/block',
      pullable = false,
      pushable = false,
      maximum_moves = 0,
    })
  end
end
```

**Comment by christopho** [comment]
This is actually normal. The coordinates used for ground detection are not the origin point but something called the ground point. See the doc of entity:get_ground_position(). There is a difference of 2 pixels.

**Comment by mattias-p** [comment]
That explains it. Great, thanks!

**Comment by christopho** [comment]
Thanks for the detailed issue report!
